/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SorteoRouteImport } from './routes/sorteo'
import { Route as TemasRouteImport } from './routes/temas'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteoRoute = SorteoRouteImport.update({
  id: '/sorteo',
  path: '/sorteo',
  getParentRoute: () => rootRouteImport,
} as any)
const TemasRoute = TemasRouteImport.update({
  id: '/temas',
  path: '/temas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/config': typeof ConfigRoute
  '/login': typeof LoginRoute
  '/sorteo': typeof SorteoRoute
  '/temas': typeof TemasRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/config': typeof ConfigRoute
  '/login': typeof LoginRoute
  '/sorteo': typeof SorteoRoute
  '/temas': typeof TemasRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/config': typeof ConfigRoute
  '/login': typeof LoginRoute
  '/sorteo': typeof SorteoRoute
  '/temas': typeof TemasRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/config'
    | '/login'
    | '/sorteo'
    | '/temas'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/config'
    | '/login'
    | '/sorteo'
    | '/temas'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/config'
    | '/login'
    | '/sorteo'
    | '/temas'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  ConfigRoute: typeof ConfigRoute
  LoginRoute: typeof LoginRoute
  SorteoRoute: typeof SorteoRoute
  TemasRoute: typeof TemasRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteo': {
      id: '/sorteo'
      path: '/sorteo'
      fullPath: '/sorteo'
      preLoaderRoute: typeof SorteoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temas': {
      id: '/temas'
      path: '/temas'
      fullPath: '/temas'
      preLoaderRoute: typeof TemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  ConfigRoute: ConfigRoute,
  LoginRoute: LoginRoute,
  SorteoRoute: SorteoRoute,
  TemasRoute: TemasRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
